package ssm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.pojo.Department;
import ssm.pojo.DepartmentExample;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    long countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    Department selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_DEPT
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByPrimaryKey(Department record);
}