package ssm.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import ssm.pojo.Employee;
import ssm.pojo.EmployeeExample;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    List<Employee> selectByExampleWithDept(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    Employee selectByPrimaryKey(Integer empId);

    Employee selectByPrimaryKeyWithDept(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_EMP
     *
     * @mbg.generated Thu Feb 21 22:16:53 CST 2019
     */
    int updateByPrimaryKey(Employee record);
}